services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: "3306"
      MYSQL_DATABASE: access
      MYSQL_USER: root
      MYSQL_PASSWORD: root
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: access
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: db
    ports:
      - "8081:80"
