services:
  web:
    image: php:8.3-apache
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: access
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: db
    ports:
      - "8081:80"
